### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by jmelberg-okta** [kewp/okta-android#1]
Overall it looks good! Just a few comments/suggestions:

- We can remove this [unused import](https://github.com/kewp/okta-android/blob/master/app/src/main/java/com/example/karl/myapplication/LoginActivity.java#L9).
- Whenever we enter an `onTokenFailure` state, any thrown exception will be ignored. I'd suggest either:
  - Use `android.util.Log` to output the error message
  - Better: Output the error message to the UI via a textfield
- There are a few other unused imports that can be removed in `AuthorizedActivity`. [`Log`](https://github.com/kewp/okta-android/blob/master/app/src/main/java/com/example/karl/myapplication/AuthorizedActivity.java#L6) and [`AuthorizationException`](https://github.com/kewp/okta-android/blob/master/app/src/main/java/com/example/karl/myapplication/AuthorizedActivity.java#L12)
- When pushing the `LoginActivity` after logout, we aren't hiding the progress bar. We should make sure that the progress bar is shown only during the Login flow

**Comment by kewp** [comment]
Thanks, Jordan. I'll fix those issues today.

Re: the progress bar. It is hidden as soon as the init method is successful. Should that not work when logging out ? Seemed to work in testing on my side...

**Comment by jmelberg-okta** [comment]
@kewp,

I believe this depends on how the progress bar is used. IIRC, this is an indicator to show that the application has the required configuration and the initializer is successful. Once successful, hide the progress bar then show the **Authorize** button.

I'm seeing different behavior:

Initial load:
![Initial Loading](http://g.recordit.co/GtQBHRs9yV.gif)

Logout:
![Logout](http://g.recordit.co/OZ974meiuO.gif)

#

Something to consider: Do you still want the progress bar to show when a user enters an error state? Right now, it is **only** hidden when `onSuccess` is called.

As an alternative, you could move the visibility toggle to the [`onCreate` method](https://github.com/kewp/okta-android/blob/master/app/src/main/java/com/example/karl/myapplication/LoginActivity.java#L35), so regardless of the `LoginActivity` state, the progress bar will be hidden.

**Comment by kewp** [comment]
Hi Jordan.

Can you do a pull and test again ? I've wrapped the progress bar in a layout container. Apparently that is required for setting View.GONE on some platforms. Strangely, I'm not getting the same error as you.

I've also put the hiding code into the fail method, as you suggested.
